name: First workflow

run-name: ${{github.actor}} is learning how Github actions work
 
permissions:
  contents: write

on: 
  pull_request:
    branches: test-branch
    types: closed  



jobs:
  read-PR-desc:
    runs-on: ubuntu-latest
    env: 
      PR_desc: ${{github.event.pull_request.body}}
    steps:
      - name: "Print PR description"
        run: echo "This is the PR body - $PR_desc and this"

  update-version:
    runs-on: ubuntu-latest
    if: ${{github.event.pull_request.merged}}
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4

      - name: "Set up user and configure git"
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"


      - name: "Bump version"
        run: npm version patch

      - name: Push changes
        run: git push --follow-tags
